<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>QElasticWallpaper</AssemblyName>
    <RootNamespace>QElasticWallpaper</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>1.4.3</Version>
    <!-- 单文件发布时把这些去掉更干净；开发调试保留即可 -->
    <DebugType>embedded</DebugType>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

</Project>
